// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvQpyFsLyPuALNV75QuLdd8dvQxYKcs8Y',
    appId: '1:559524046424:web:18717280b7ac6e6d4a8c2d',
    messagingSenderId: '559524046424',
    projectId: 'thapar-eats',
    authDomain: 'thapar-eats.firebaseapp.com',
    storageBucket: 'thapar-eats.appspot.com',
    measurementId: 'G-KSPD7ZX2XZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1l8Pu_QsRjr7VHikFjsLHOG0JOKKenjw',
    appId: '1:559524046424:android:943ffc3ce4cde4df4a8c2d',
    messagingSenderId: '559524046424',
    projectId: 'thapar-eats',
    storageBucket: 'thapar-eats.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5b1oYsaD7NyJhX2U0ON1McrKOabPiYSQ',
    appId: '1:559524046424:ios:29dee9d61a4dd9154a8c2d',
    messagingSenderId: '559524046424',
    projectId: 'thapar-eats',
    storageBucket: 'thapar-eats.appspot.com',
    iosClientId: '559524046424-0jmks69fflt3vh1ff058e3mm5dqbj4tr.apps.googleusercontent.com',
    iosBundleId: 'com.example.thaparEats',
  );
}
